Дана целочисленная квадратная матрица. Определить:
сумму элементов в тех строках, которые не содержат отрицательных элементов;
минимум среди сумм элементов диагоналей, параллельных главной диагонали матрицы.




Для начала импортируем numpy и создадим матрицу

In [32]:
import numpy as np

m = np.matrix('1 -2 3 54 -4; 43 1 8 21 64; -983 27 0 44 32 ; 11 22 33 44 55; 7 2 98 -45 23')
print(m)

[[   1   -2    3   54   -4]
 [  43    1    8   21   64]
 [-983   27    0   44   32]
 [  11   22   33   44   55]
 [   7    2   98  -45   23]]


1. Для нахождения суммы элементов в строках, не содержащих отриц.элементов воспользуемся функцией where 

In [33]:
np.where((m >= 0).all(axis=1), m.sum(axis=1), "String contains negative element")

array([['String contains negative element'],
       ['137'],
       ['String contains negative element'],
       ['165'],
       ['String contains negative element']], dtype='<U32')

2. Сначала определим размер матрицы и создадим список с суммой элементов каждой диагонали, а затем найдём наименьшее число в этом списке

In [40]:
size = m.shape
n = size[0]

min_elems = [(np.diagonal(m, offset = i, axis1=0, axis2=1)).sum() for i in range(-n, n)]
print(min_elems)
print(f'Minimal sum of elements: ', min(min_elems))

[0, 7, 13, -863, 58, 69, 105, 56, 118, -4]
Minimal sum of elements:  -863
